services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=it_projects_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5433:5432'
