spring:
  application:
    name: IT-project-hub

  datasource:
    url: jdbc:postgresql://localhost:5433/it_projects_db
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations:
      - classpath:db/migration

jwt:
  secret: saltvfnibnvwovdfjlvsdhvnsjkcniandbcsjnvsfvbnjsxcvnsdv
  expiration: 10000
  refresh:
    expiration: 680000